# coding: utf-8
# Copyright (c) 2016, 2019, Oracle and/or its affiliates. All rights reserved.

LIFECYCLE_STATE_DETAILS_PENDING_SUBMISSION = "PENDING_SUBMISSION"
LIFECYCLE_STATE_DETAILS_PENDING_APPROVAL = "PENDING_APPROVAL"
LIFECYCLE_STATE_DETAILS_CUSTOMER_PROCESSING = "CUSTOMER_PROCESSING"
LIFECYCLE_STATE_DETAILS_CUSTOMER_RECEIVED = "CUSTOMER_RECEIVED"
LIFECYCLE_STATE_DETAILS_ORACLE_SHIPPED = "ORACLE_SHIPPED"
OBJECT_STORAGE_BUCKET_TYPE_ARCHIVE = "Archive"
