# coding: utf-8
# Copyright (c) 2016, 2021, Oracle and/or its affiliates. All rights reserved.

ROVER_WORKLOAD_TYPE_IMAGE = "image"
ROVER_CLUSTER_STATION_TYPE = "STATION"
ROVER_CLUSTER_STANDALONE_TYPE = "STANDALONE"
ROVER_UPGRADE_BUNDLE_UPLOAD_BUCKET = "rover-system-upgrade-staging"
ROVER_DIAGNOSTIC_BUNDLE_API_BASE_PATH = "/20220901/bundles"
DEFAULT_ROVER_DEVICE_ENDPOINT = "https://vcluster-1-red-1:23060"
TERMINAL_STATES = ["IMPORTED", "FAILURE", "DECRYPTION_FAILURE", "ENCRYPTION_KEY_IMPORT_FAILURE"]
NON_TERMINAL_STATES = ["INITIALIZING", "VALIDATING_VERSION", "DECRYPTED", "DECRYPTING", "VERIFYING_SIGNATURE",
                       "FINALIZING"]
