name: Auto Approve
on: pull_request_target
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'oci-dex-release-bot'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto-approved by GitHub Actions"
