# Sanity test OCI CLI installer

name: OCI CLI Install Test

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      cli-release:
        description: 'Release tag to test, e.g. "v3.33.3"'
        required: true

jobs:

  sanity-test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        arch: ["x64", "arm64"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.6"
          - os: ubuntu-latest
            arch: "arm64"
          - os: windows-latest
            arch: "arm64"
        include:
          - os: ubuntu-20.04
            python-version: "3.6"

    steps:

      - name: Check out release
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.cli-release }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install CLI using install.sh
        run: |
          ./scripts/install/install.sh --accept-all-defaults

      - name: Check basic CLI commands
        run: |
          oci --version
          oci compute instance launch --generate-full-command-json-input
